### ISSUE TITLE
General Error: Syntax Error in regular expression

### ISSUE THREAD

**Issue by Shoekrates** [inspiredminds/contao-file-usage#1]
Hi,
my System: Contao 4.13.16, PHP Version 8.0.28

Just installed the extension but after clicking on the file usage icon of a certain file in the file management gives a general error:

`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 3688 Syntax error in regular expression on line 1, character 1`

Clicking the general option to show all unused files gives the same error.

/var/log
`
request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 3688 Syntax error in regular expression on line 1, character 1." at /var/www/zzzzzz/html/yyyyyy/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 117 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 3688): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 3688 Syntax error in regular expression on line 1, character 1. at /var/www/zzzzzz/html/yyyyyy/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:117)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 3688): SQLSTATE[HY000]: General error: 3688 Syntax error in regular expression on line 1, character 1. at /var/www/zzzzzz/html/yyyyyy/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 3688 Syntax error in regular expression on line 1, character 1. at /var/www/zzzzzz/html/yyyyyy/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121)"} []
`

Any ideas?

**Comment by fritzmg** [comment]
Which MySQL/MariaDB version?

**Comment by Shoekrates** [comment]
Should be a „Percona Server for MySQL 8.0.31-23“. This is what I read from phpMyAdmin. Hoster is udmedia.de.
![grafik](https://user-images.githubusercontent.com/1934944/224280747-ca729ca1-20cc-4511-965e-7ab4a311135c.png)

**Comment by fritzmg** [comment]
Yes, I think this is an incompatibility with MySQL at the moment. It currently only works with MariaDB.

**Comment by fritzmg** [comment]
There will be a rewrite that improves performance, this will also (likely) take care of this issue.

**Comment by Shoekrates** [comment]
Thanks for the quick update – I can confirm that it works in my setting.
