### ISSUE TITLE
No refresh on global operation

### ISSUE THREAD

**Issue by falkgeist** [inspiredminds/contao-file-usage#3]
The global operation "Unused files" (german: "Unbenutzte Dateien") does not automatically update the cache. This might be intended behavior, but it is not expected.

The expected behavior would be that the list is up-to-date when it is first clicked.

The operation has a different icon, which is already hinting at the possibility to reload the list on a subsequent click, but the name of the operation is the same, so one doesn't necessarily notice this possiblity.

I suggest that either the expected behavior is implemented (`refresh=1` together with `unused=1`?) or the necessity to reload the list by clicking a second time is mentioned in the (already existing) warning message, together with a different label name for the global operation (e.g. "Refresh unused files"/"Unbenutzte Dateien aktualisieren").

**Comment by fritzmg** [comment]
Done in b5c3274
